easy_admin:
    site_name: 'Admin'
    formats:
        datetime: 'd/m/Y h:i'
    entities:
       User:
          class: App\Entity\User
          label: 'Подписчики'
          list:
            actions: ['show']
            title: "Список подписчиков"
            fields:
                  - name
                  - { property: 'phone', label: 'phone', type: 'tel' }
                  - { property: 'email', label: 'Contact' }
                  - { property: 'age', label: 'Age' }
                  - { property: 'city', label: 'city' }
                  - { property: 'created', label: 'Date' }
                  - { property: 'active', label: 'active' }
                  - { property: 'refToken', label: 'ref link', type: 'url' }

       Category:
          class: App\Entity\Category
          label: 'Категории'
          list:
            title: "Категории"
            fields:
                 - title
                 - description
                 - { property: 'url', label: 'link', type: 'url' }
                 - { property: 'image', type: 'image', base_path: '%app.path.upload%' }
          form:
            fields:
                - title
                - description
                - url
                - { property: 'imageFile', type: 'vich_image' }
                - { property: 'imageBannerFile', type: 'vich_image' }

       Product:
          class: App\Entity\Product
          label: 'Видео'
          list:
            title: "Вебинары"
            fields:
                - title
                - description
                - { property: 'url', label: 'link', type: 'url' }
                - { property: 'file', type: 'image', base_path: '%app.path.upload%' }
                - category
          form:
              fields:
                 - title
                 - description
                 - url
                 - category
                 - { property: 'imageFile', type: 'vich_image' }
              form_options: { validation_groups: ['Default'] }
          new:
             form_options: { validation_groups: ['Default', 'Product'] }
          edit:
             form_options: { validation_groups: ['not_existing_group'] }




    design:
        brand_color: 'rgba(26, 188, 156, 0.85)'
