security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    role_hierarchy:
            ROLE_ADMIN: [ROLE_USER]
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
    providers:
        #in_memory: { memory: ~ }
        in_memory:
                    memory:
                        users:
                            admin:
                                password: $2y$13$JV5ZydF9Qq03rqDtoTztJuekw4u026DAu6sqDs0dCk2HUtBUNDYb6
                                roles: 'ROLE_ADMIN'

        db:
          entity:
              class: App\Entity\User
              property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: in_memory
            form_login:
                login_path: login
                check_path: login
            logout: true
            anonymous: ~




    access_control:
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/book/, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: ['IS_AUTHENTICATED_ANONYMOUSLY','ROLE_USER'] }
        - { path: ^/, role: IS_AUTHENTICATED_ANONYMOUSLY }






